---
galaxy_info:
  author: Conrado Buhrer
  description: creates system accounts
  company: icekernel.com
  license: Apache 2.0
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
dependencies: []
